export default function ScrollIndicator() {
  return (
    <div
      className="
        absolute
        bottom-10
        left-1/2
        z-20
        hidden
        -translate-x-1/2
        flex-col
        items-center
        gap-3
        lg:flex
      "
    >
      <span
        className="
          text-[10px]
          uppercase
          tracking-[0.45em]
          text-zinc-400
        "
      >
        Scroll
      </span>

      <div
        className="
          flex
          h-14
          w-[1px]
          justify-center
          bg-white/20
        "
      >
        <div
          className="
            mt-2
            h-2
            w-2
            rounded-full
            bg-[var(--vs-accent)]
            animate-bounce
          "
        />
      </div>
    </div>
  );
}